export const REQUEST_BOOKS = 'REQUEST_BOOK';
export const RECEIVE_BOOKS = 'RECEIVE_BOOK';
export const REQUEST_INCREMENT_LIKE = 'REQUEST_INCREMENT_LIKE';
export const RECEIVE_INCREMENT_LIKE = 'RECEIVE_INCREMENT_LIKE';
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const REQUEST_ADD_COMMENT = 'REQUEST_ADD_COMMENT';
export const RECEIVE_ADD_COMMENT = 'RECEIVE_ADD_COMMENT';

