export const REQUEST_BOOKS = 'REQUEST_BOOK';
export const RECEIVE_BOOKS = 'RECEIVE_BOOK';
export const REQUEST_INCREMENT_LIKE = 'REQUEST_INCREMENT_LIKE';
export const RECEIVE_INCREMENT_LIKE = 'RECEIVE_INCREMENT_LIKE';
export const ADD_COMMENT = 'ADD_COMMENT';
